"""Sigma rule generation from extracted IOCs and threat intelligence."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

import yaml  # type: ignore[import-untyped]


class SigmaRuleGenerator:
    """Generate Sigma rules from IOCs for SIEM detection.

    Produces YAML-format Sigma rules that can be imported into Splunk,
    Elastic, Sentinel, etc.
    """

    def generate_from_iocs(
        self,
        iocs: dict[str, list],
        title: str = "",
        description: str = "",
        level: str = "medium",
    ) -> str:
        """Generate a Sigma rule from extracted IOCs.

        Args:
            iocs: Dict with IOC lists (e.g. {"ipv4": [...], "domains": [...]}).
            title: Rule title.
            description: Rule description.
            level: Severity level (low, medium, high, critical).

        Returns:
            Sigma rule as YAML string.
        """
        detection: dict[str, list] = {}
        condition_parts = []

        if iocs.get("ipv4"):
            detection["DestinationIp"] = iocs["ipv4"]
            detection["SourceIp"] = iocs["ipv4"]
            condition_parts.append("selection_ips")
        if iocs.get("domains"):
            detection["DestinationHostname"] = iocs["domains"]
            condition_parts.append("selection_domains")
        if iocs.get("urls"):
            detection["CommandLine|contains"] = iocs["urls"]
            condition_parts.append("selection_urls")
        if iocs.get("sha256"):
            detection["Hashes"] = iocs["sha256"]
            condition_parts.append("selection_hashes")
        if iocs.get("md5"):
            if "Hashes" in detection:
                detection["Hashes"].extend(iocs["md5"])
            else:
                detection["Hashes"] = iocs["md5"]
            if "selection_hashes" not in condition_parts:
                condition_parts.append("selection_hashes")
        if iocs.get("cves"):
            detection["CommandLine|contains"] = iocs.get("cves", [])
            condition_parts.append("selection_cves")
        if iocs.get("emails"):
            detection["TargetFilename|contains"] = iocs["emails"]
            condition_parts.append("selection_emails")

        if not condition_parts:
            condition_parts = ["selection"]

        rule: dict[str, Any] = {
            "title": title or "Auto-generated Sigma Rule from IOCs",
            "id": str(uuid.uuid4()),
            "status": "experimental",
            "description": description or "Generated by Black Onyx from extracted IOCs",
            "author": "Black Onyx",
            "date": datetime.now().strftime("%Y/%m/%d"),
            "level": level,
            "logsource": {"product": "windows", "service": "sysmon"},
            "detection": {
                **detection,
                "condition": " or ".join(condition_parts),
            },
        }
        return yaml.dump(rule, default_flow_style=False, sort_keys=False)

    def generate_from_mitre_technique(
        self,
        technique_id: str,
        technique_name: str,
        tactic: str | list[str],
        iocs: dict[str, list] | None = None,
    ) -> str:
        """Generate a Sigma rule mapped to a MITRE ATT&CK technique."""
        tactics = [tactic] if isinstance(tactic, str) else tactic
        rule: dict[str, Any] = {
            "title": f"{technique_name} - {technique_id}",
            "id": str(uuid.uuid4()),
            "status": "experimental",
            "description": f"Detection for MITRE ATT&CK technique {technique_id}: {technique_name}",
            "author": "Black Onyx",
            "date": datetime.now().strftime("%Y/%m/%d"),
            "level": "high",
            "tags": [f"attack.{t}" for t in tactics],
            "logsource": {"product": "windows", "service": "sysmon"},
            "detection": {
                "condition": "selection",
            },
        }
        if iocs:
            detection = {}
            if iocs.get("ipv4"):
                detection["DestinationIp"] = iocs["ipv4"]
            if iocs.get("domains"):
                detection["DestinationHostname"] = iocs["domains"]
            if iocs.get("sha256"):
                detection["Hashes"] = iocs["sha256"]
            rule["detection"]["selection"] = detection
        return yaml.dump(rule, default_flow_style=False, sort_keys=False)
