"""YARA rule generation from extracted strings, hashes, and patterns."""

from __future__ import annotations

from datetime import datetime


class YARARuleGenerator:
    """Generate YARA rules from extracted IOCs and strings.

    Produces text-format YARA rules for file scanning and malware detection.
    """

    def generate_from_iocs(
        self,
        iocs: dict[str, list],
        rule_name: str = "",
        tags: list[str] | None = None,
    ) -> str:
        """Generate a YARA rule from extracted IOCs.

        Args:
            iocs: Dict with IOC lists.
            rule_name: Name for the YARA rule.
            tags: Optional tags for the rule.

        Returns:
            YARA rule as a string.
        """
        name = rule_name or "AutoGeneratedRule"
        tags_str = " ".join(f":{t}" for t in (tags or []))
        conditions: list[str] = []

        lines = [
            f"rule {name} {tags_str}{{",
            "    meta:",
            '        description = "Auto-generated by Black Onyx"',
            f'        generated = "{datetime.now().isoformat()}"',
            "    strings:",
        ]

        idx = 0
        if iocs.get("sha256"):
            for h in iocs["sha256"]:
                lines.append(f'        $hash{idx} = "{h}"')
                conditions.append(f"$hash{idx}")
                idx += 1
        if iocs.get("sha1"):
            for h in iocs["sha1"]:
                lines.append(f'        $hash{idx} = "{h}"')
                conditions.append(f"$hash{idx}")
                idx += 1
        if iocs.get("md5"):
            for h in iocs["md5"]:
                lines.append(f'        $hash{idx} = "{h}"')
                conditions.append(f"$hash{idx}")
                idx += 1
        if iocs.get("domains"):
            for d in iocs["domains"][:10]:
                lines.append(f'        $domain{idx} = "{d}" nocase')
                conditions.append(f"$domain{idx}")
                idx += 1
        if iocs.get("urls"):
            for u in iocs["urls"][:10]:
                lines.append(f'        $url{idx} = "{u}" nocase')
                conditions.append(f"$url{idx}")
                idx += 1
        if iocs.get("cves"):
            for c in iocs["cves"]:
                lines.append(f'        $cve{idx} = "{c}" nocase')
                conditions.append(f"$cve{idx}")
                idx += 1
        if iocs.get("emails"):
            for e in iocs["emails"][:5]:
                lines.append(f'        $email{idx} = "{e}" nocase')
                conditions.append(f"$email{idx}")
                idx += 1

        if not conditions:
            conditions = ["any of them"]

        lines.append("    condition:")
        lines.append(f"        {' or '.join(conditions)}")
        lines.append("}")
        return "\n".join(lines)
