global:
  resolve_timeout: 5m

route:
  receiver: webhook-default
  group_by: [alertname, severity]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: webhook-default
    webhook_configs:
      - url: http://notification-service:8086/api/v1/notifications/test
        send_resolved: true
        http_config: {}

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: [alertname]
